Controllers/BusController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineBusTransportation.Data;
using OnlineBusTransportation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineBusTransportation.Controllers
{
    public class BusController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public BusController(UserManager<ApplicationUser> userManager, ApplicationDbContext context)
        {
            _context = context;
            _userManager = userManager;

        }
        public async Task<IActionResult> SearchBuses()
        {
            return View();
        }
            [HttpPost]
        public async Task<IActionResult> SearchBuses(IFormCollection form)
        {
            string departureid = form["Departure"];
            string destinationid = form["destination"];
            var departure = _context.Departure.Where(d => d.ID == Convert.ToInt32(departureid)).FirstOrDefault();
            var destination = _context.Destination.Where(d => d.ID == Convert.ToInt32(destinationid)).FirstOrDefault();

            var date = form["datepicker"].ToString() as string;
            List<BusInfoViewModel> results = null; 
            if (!string.IsNullOrEmpty(date))
            {

            
            DateTime journeydate =Convert.ToDateTime(form["datepicker"]);

                results = await (from businfo in _context.BusInfo
                           join buses in _context.Buses on businfo.BusID equals buses.ID
                           select new BusInfoViewModel()
                           {
                               BusID=buses.ID,
                               BusNumber=buses.BusNumber,
                               Name=buses.Name,
                               Destination=businfo.Destination,
                               Departure=businfo.Departure,
                               datetime=businfo.datetime,
                               AvailableSeats=businfo.availableSeats,
                               BookedSeats=businfo.BookedSeats
                           }).Where(b => b.Departure == departure.Name.ToString() && b.Destination == destination.Name.ToString() && b.datetime == journeydate).ToListAsync();
            }
            else
            {
                results = await (from businfo in _context.BusInfo
                                     join buses in _context.Buses on businfo.BusID equals buses.ID
                                     select new BusInfoViewModel()
                                     {
                                         BusID = buses.ID,
                                         BusNumber = buses.BusNumber,
                                         Name = buses.Name,
                                         Destination = businfo.Destination,
                                         Departure = businfo.Departure,
                                         datetime = businfo.datetime,
                                         AvailableSeats = businfo.availableSeats,
                                         BookedSeats = businfo.BookedSeats
                                     }).Where(b => b.Departure == departure.Name.ToString() && b.Destination == destination.Name.ToString()).ToListAsync();

            }
            return View(results);
        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using OnlineBusTransportation.Data;
using OnlineBusTransportation.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineBusTransportation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        public HomeController(ApplicationDbContext context,RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _context = context;

        }

        public IActionResult Index()
        {
            ViewData["Departure"] = new SelectList(_context.Departure, "ID", "Name");
            ViewData["Destination"] = new SelectList(_context.Destination, "ID", "Name");

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        //creating roles
        public async Task CreateRolesandUsers()
        {

            bool x = await _roleManager.RoleExistsAsync("Admin");
            if (!x)
            {
                // first we create Admin role   
                var role = new IdentityRole();
                role.Name = "Admin";
                await _roleManager.CreateAsync(role);
            }
            //Then we create a user 
            var user = new ApplicationUser();
            user.UserName = "Admin";
            user.Email = "admin@gmail.com";
            string userPWD = "Abc123!";
            //for user
            var customer = new ApplicationUser();
            customer.UserName = "customer1@gmail.com";
            customer.Email = "customer1@gmail.com";
            string customerPWD = "Abc123!";

            //for staff
            var userstaff = new ApplicationUser();
            userstaff.UserName = "Staff1@gmail.com";
            userstaff.Email = "Staff1@gmail.com";
            string userstaffPWD = "Abc123!";

            IdentityResult chkUser = await _userManager.CreateAsync(user, userPWD);
            IdentityResult chkUsercustomer = await _userManager.CreateAsync(customer, customerPWD);
            IdentityResult chkUserstaff = await _userManager.CreateAsync(userstaff, userstaffPWD);

            //Add default User to Role Admin    
            if (chkUser.Succeeded)
            {
                var result = await _userManager.AddToRoleAsync(user, "Admin");
            }
            if (chkUsercustomer.Succeeded)
            {
                var result = await _userManager.AddToRoleAsync(customer, "User");
            }
            if (chkUserstaff.Succeeded)
            {
                var result = await _userManager.AddToRoleAsync(userstaff, "Staff");
            }
        }
}
}

Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using OnlineBusTransportation.Data;

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_LayoutWebsite.cshtml";
}

<div class="container">
    @if (User.Identity.IsAuthenticated)
    {
        <br />
        <h3>Welcome @UserManager.GetUserName(User)!</h3>
        <br />
        <br />
    }
    else
    {
        <div class="col-md-5 bann-info1 wow fadeInLeft animated" data-wow-delay=".5s">
            <i class="fa fa-columns"></i>
            <h3>WORLD'S MOST TRAVEL BRAND</h3>
        </div>
        <div class="col-md-7 bann-info wow fadeInRight animated" data-wow-delay=".5s">

            <form method="post" asp-action="SearchBuses" asp-controller="Bus">

                <h2>Online Tickets with Zero Booking Fees</h2>
                <div class="ban-top">
                    <div class="bnr-left">
                        <label class="inputLabel">Departure</label>
                       
                        <select name="Departure" id="Departure" class="form-control" asp-items="@ViewBag.Departure"></select>

                    </div>
                    <div class="bnr-left">

                        <label class="inputLabel">Destination</label>
                        <select name="destination" id="destination" class="form-control" asp-items="@ViewBag.Destination"></select>

                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="ban-bottom">
                    <div class="bnr-right">
                        <label class="inputLabel">Date of Journey</label>
                        <input class="form-control" id="datepicker" name="datepicker" type="datetime-local"  />

                        
                        @* <input class="date" id="datepicker" name="datepicker" type="text" value="dd/mm/yyyy" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'dd/mm/yyyy';}" required=>*@
                    </div>
                    <div class="clearfix"></div>
                    <!---start-date-piker---->
                    <link rel="stylesheet" href="css/jquery-ui.css" />
                    <script src="js/jquery-ui.js"></script>
                    <script>
                        $(function () {
                            $("#datepicker,#datepicker1").datepicker({ dateFormat: 'dd/mm/yy' }).val();
                        });</script>
                    <!---/End-date-piker---->
                </div>
                <div class="sear">
                    <button class="seabtn" type="submit">Search Buses</button>
                </div>

            </form>

        </div>
    }
    <div class="clearfix"></div>
</div>
<!---728x90--->
<!--- /banner ---->
<!--- rupes ---->
<div class="container">
    <div class="rupes">
        <div class="col-md-4 rupes-left wow fadeInDown animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInDown;">
            <div class="rup-left">
                <a href="offers.html"><i class="fa fa-usd"></i></a>
            </div>
            <div class="rup-rgt">
                <h3>UP TO USD. 50 OFF</h3>
                <h4><a href="offers.html">TRAVEL SMART</a></h4>
                <p>CODE:YBMAR12<br>Book Using Pay Money</p>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="col-md-4 rupes-left wow fadeInDown animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInDown;">
            <div class="rup-left">
                <a href="offers.html"><i class="fa fa-h-square"></i></a>
            </div>
            <div class="rup-rgt">
                <h3>UP TO 70% OFF</h3>
                <h4><a href="offers.html">ON HOTELS ACROSS WORLD</a></h4>
                <p>Offer CODE:YBMAR12</p>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="col-md-4 rupes-left wow fadeInDown animated animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeInDown;">
            <div class="rup-left">
                <a href="offers.html"><i class="fa fa-mobile"></i></a>
            </div>
            <div class="rup-rgt">
                <h3>FLAT USD. 50 OFF</h3>
                <h4><a href="offers.html">BUS APP OFFER</a></h4>
                <p>book via the yellow Bus App<br>CODE:YBMAR12</p>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!---728x90--->
<!--- /rupes ---->
<!---holiday---->
<div class="container">
    <div class="holiday">
        <div class="col-md-3 holiday-left animated wow fadeInUp animated" data-wow-duration="1200ms" data-wow-delay="500ms" style="visibility: visible; animation-duration: 1200ms; animation-delay: 500ms; animation-name: fadeInUp;">
            <img src="~/images/4.jpg" class="img-responsive" alt="">
        </div>
        <div class="col-md-6 holiday-mid animated wow fadeInUp animated" data-wow-duration="1200ms" data-wow-delay="500ms" style="visibility: visible; animation-duration: 1200ms; animation-delay: 500ms; animation-name: fadeInUp;">
            <h3>Travel Holiday Packages</h3>
            <p>Private Guide and Driver in any language and in any departure date. For more information please contact us....</p>
        </div>
        <div class="col-md-3 holiday-left animated wow fadeInUp animated" data-wow-duration="1200ms" data-wow-delay="500ms" style="visibility: visible; animation-duration: 1200ms; animation-delay: 500ms; animation-name: fadeInUp;">
            <img src="~/images/5.jpg" class="img-responsive" alt="">
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!---/holiday---->
<!---track---->
<div class="container">
    <div class="track">
        <div class="col-md-6 track-right wow fadeInLeft animated" data-wow-delay=".5s">
            <a href="#"><img src="~/images/map1.png" class="img-responsive" alt=""></a>
        </div>
        <div class="col-md-6 track-left wow fadeInRight animated" data-wow-delay=".5s">
            <h3>TRACK MY BUS</h3>
            <p>First of its own kind,bus tracking feature on bus</p>
            <a href="#" class="learn">Learn More</a>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!--- /track ---->
<!--- routes ---->
<div class="routes">
    <div class="container">
        <div class="col-md-4 routes-left wow fadeInRight animated" data-wow-delay=".5s">
            <div class="rou-left">
                <a href="#"><i class="fa fa-truck"></i></a>
            </div>
            <div class="rou-rgt wow fadeInDown animated" data-wow-delay=".5s">
                <h3>80000</h3>
                <p>ROUTES</p>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="col-md-4 routes-left">
            <div class="rou-left">
                <a href="#"><i class="fa fa-user"></i></a>
            </div>
            <div class="rou-rgt">
                <h3>1900</h3>
                <p>BUS OPERATORS</p>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="col-md-4 routes-left wow fadeInRight animated" data-wow-delay=".5s">
            <div class="rou-left">
                <a href="#"><i class="fa fa-ticket"></i></a>
            </div>
            <div class="rou-rgt">
                <h3>7,00,00,000+</h3>
                <p>TICKETS SOLD</p>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>