Controllers/BusesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineBusTransportation.Data;
using OnlineBusTransportation.Models;

namespace OnlineBusTransportation.Controllers
{
    [Authorize(Roles = "Staff")]
    public class BusesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public BusesController(UserManager<ApplicationUser> userManager,ApplicationDbContext context)
        {
            _context = context;
            _userManager = userManager;

        }
        //show seats information
        
              public async Task<IActionResult> ShowBookedSeats(int? id)
        {
            var buses = await _context.Buses
                  .FirstOrDefaultAsync(m => m.ID == id);
            TempData["Name"] = buses.Name;
            TempData["BusNumber"] = buses.BusNumber;
            TempData["ID"] = buses.ID;


            return View(await _context.BusInfo.Where(B => B.BusID == id).ToListAsync());
        }
        //show all booking money received
        public async Task<IActionResult> ShowAllBooking(int businfoid)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); // will give the user's userId

            ShowBookingViewModel SB = new ShowBookingViewModel();
            var results = await (from businfo in _context.BusInfo
                                 join booking in _context.UsersBooking on businfo.ID equals booking.BusInfoID
                                 join bus in _context.Buses on businfo.BusID equals bus.ID

                                 select new ShowBookingViewModel()
                                 {
                                     userid = booking.UserID,
                                     BookingID = booking.BookingID,
                                     BusInfoID = booking.BusInfoID,
                                     BusNumber = bus.BusNumber,
                                     Name = bus.Name,
                                     Destination = businfo.Destination,
                                     Departure = businfo.Departure,
                                     datetime = businfo.datetime,
                                     Seats = booking.Seats,
                                     price = booking.price
                                 }).Where(b => b.BusInfoID == businfoid).ToListAsync();

            return View(results);
        }

        //show buses routes

        public async Task<IActionResult> ShowRoutes(int? id)
        {
            var buses = await _context.Buses
                  .FirstOrDefaultAsync(m => m.ID == id);
            TempData["Name"] = buses.Name;
            TempData["BusNumber"] = buses.BusNumber;
            TempData["ID"] = buses.ID;


            return View(await _context.BusInfo.Where(B => B.BusID == id).ToListAsync());
        }

        // GET: Buses
        public async Task<IActionResult> Index()
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);

            return View(await _context.Buses.Where(B=>B.CreatedBy==applicationUser.Id).ToListAsync());
        }
        //users feedback
        public async Task<IActionResult> ViewFeedback()
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);

            TableManager TableManagerObj = new TableManager("UsersFeedback");
            List<UsersFeedback> usersfeedbacklist =TableManagerObj.RetrieveEntity<UsersFeedback>();
            return View(usersfeedbacklist.Where(u=>u.CompanyID==applicationUser.Id).ToList());
        }


        //show seats
        public async Task<IActionResult> Seats()
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);

            return View(await _context.Buses.Where(B => B.CreatedBy == applicationUser.Id).ToListAsync());
        }

        // GET: Buses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buses = await _context.Buses
                .FirstOrDefaultAsync(m => m.ID == id);
            if (buses == null)
            {
                return NotFound();
            }

            return View(buses);
        }

        // GET: Buses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Buses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Type,BusCapacity,BusNumber")] Buses buses)
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);
            buses.CreatedBy = applicationUser.Id;
            buses.CreatedDate = DateTime.Now;
            
            if (ModelState.IsValid)
            {
                _context.Add(buses);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(buses);
        }

        // GET: Buses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buses = await _context.Buses.FindAsync(id);
            if (buses == null)
            {
                return NotFound();
            }
            return View(buses);
        }

        // POST: Buses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Type,BusCapacity,BusNumber")] Buses buses)
        {
            ApplicationUser applicationUser = await _userManager.GetUserAsync(User);
            buses.CreatedBy = applicationUser.Id;
            buses.CreatedDate = DateTime.Now;

            if (id != buses.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(buses);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BusesExists(buses.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(buses);
        }

        // GET: Buses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buses = await _context.Buses
                .FirstOrDefaultAsync(m => m.ID == id);
            if (buses == null)
            {
                return NotFound();
            }

            return View(buses);
        }

        // POST: Buses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var buses = await _context.Buses.FindAsync(id);
            _context.Buses.Remove(buses);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        //add bus route information
        public async Task<IActionResult> AddRoute(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buses = await _context.Buses
                .FirstOrDefaultAsync(m => m.ID == id);
            if (buses == null)
            {
                return NotFound();
            }
            ViewData["Departure"] = new SelectList(_context.Departure, "ID", "Name");
            ViewData["Destination"] = new SelectList(_context.Destination, "ID", "Name");

            return View(buses);
        }

        [HttpPost]
        public async Task<IActionResult> CreateRoute(IFormCollection form)
        {
            int busid =Convert.ToInt32(form["ID"]);
            string departureid = form["Departure"];
            string destinationid = form["Destination"];
            var departure = _context.Departure.Where(d => d.ID ==Convert.ToInt32(departureid)).FirstOrDefault();
            var destination = _context.Destination.Where(d => d.ID == Convert.ToInt32(destinationid)).FirstOrDefault();

            DateTime date =Convert.ToDateTime(form["DepartureDate"]);
            var bus = _context.Buses.Where(b => b.ID == busid).FirstOrDefault();
            BusInfo b = new BusInfo();
            b.BusID = busid;
            b.Departure = departure.Name;
            b.Destination = destination.Name;
            b.datetime = date;
            b.availableSeats =40;
            b.BookedSeats = 0;
            _context.Add(b);
            await _context.SaveChangesAsync();
            return RedirectToAction("ShowRoutes", new { id = busid });
            
            //return View();
        }
        //Edit routes
        public async Task<IActionResult> EditRoute(int? id)
        {
            if (id == null)
            {

Views/Buses/AddRoute.cshtml
@model OnlineBusTransportation.Models.Buses

@{
    ViewData["Title"] = "Add Route Information";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Buses</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRoute">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" name="ID" id="ID" />

            <div class="form-group">
                <label class="control-label">Bus Name</label>
                <input asp-for="Name" readonly class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Bus Number</label>
                <input asp-for="BusNumber" readonly class="form-control" />
                <span asp-validation-for="BusNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Departure</label>
                <select name="Departure" id="Departure" class="form-control" asp-items="@ViewBag.Departure"></select>

            </div>
            <div class="form-group">
                <label class="control-label">Destination</label>
                <select name="destination" id="destination"  class="form-control" asp-items="@ViewBag.Destination"></select>

            </div>
            <div class="form-group">
                <label class="control-label">Departure Date</label>
                <input type="datetime-local" name="DepartureDate" required class="form-control" id="DepartureDate" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Buses/Create.cshtml
@model OnlineBusTransportation.Models.Buses

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Buses</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label  class="control-label">Bus Name</label>
                <input asp-for="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control">
                    <option value="Luxury">Luxury</option>
                    <option value="Economy">Economy</option>
                  
                </select>

                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Bus Number</label>
                <input asp-for="BusNumber" class="form-control" required />
                <span asp-validation-for="BusNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Buses/Delete.cshtml
@model OnlineBusTransportation.Models.Buses

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Buses</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
           <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BusNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BusNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Buses/Details.cshtml
@model OnlineBusTransportation.Models.Buses

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Buses</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BusNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BusNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Buses/Edit.cshtml
@model OnlineBusTransportation.Models.Buses

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Buses</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label class="control-label">Bus Name</label>
                <input asp-for="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control">
                    <option value="Luxury">Luxury</option>
                    <option value="Economy">Economy</option>

                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="BusNumber" class="control-label"></label>
                <input asp-for="BusNumber" class="form-control" required />
                <span asp-validation-for="BusNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Buses/EditRoute.cshtml
@model OnlineBusTransportation.Models.BusInfo

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Update</h1>

<h4>Bus Route</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditRoute" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" name="ID" id="ID" />
            <input type="hidden" asp-for="BusID" name="BusID" id="BusID" />
            <div class="form-group">
                <label class="control-label">Bus Name</label>
                @{ var busname = TempData["BusName"];}
                <input value='@busname' readonly class="form-control"  />

            </div>

            <div class="form-group">
                <label class="control-label">Bus Number</label>
                <input value='@TempData["BusNumber"]' readonly class="form-control" />

            </div>
            <div class="form-group">
                <label class="control-label">Departure</label>
                <select  class="form-control" id="Departure" name="Departure"  asp-items="@ViewBag.Departure"></select>

            </div>
            <div class="form-group">
                <label class="control-label">Destination</label>
                <select    class="form-control" id="Destination" name="Destination" asp-items="@ViewBag.Destination"></select>

            </div>
            <div class="form-group">
                <label class="control-label">Departure Date</label>
                <input type="datetime-local" asp-for="datetime" required class="form-control" />
                <span asp-validation-for="datetime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ShowRoutes" asp-route-id="@Model.BusID">Back to List</a>

    
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Buses/Index.cshtml
@model IEnumerable<OnlineBusTransportation.Models.Buses>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List of all Buses</h1>


<button type="button" style="float:right;" class="btn btn-success" onclick="location.href='@Url.Action("Create", "Buses")'">Add New Bus</button>

   @* <a asp-action="Create">Add New Bus</a>*@

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>Update Information</th>
            <th>Add Route</th>
            <th>Routes</th>


        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
            <td>
                <a asp-action="AddRoute" asp-route-id="@item.ID">Add Route</a>
            </td>
            <td>
                <a asp-action="ShowRoutes" asp-route-id="@item.ID">Show Routes</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Buses/RouteDelete.cshtml
@model OnlineBusTransportation.Models.BusInfo

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this route?</h3>
<div>
    <h4>Route</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Bus Name:
        </dt>
        <dd class="col-sm-10">
            @TempData["BusName"]

        </dd>
        <dt class="col-sm-2">
            Bus Number:
        </dt>
        <dd class="col-sm-10">
            @TempData["BusNumber"]

        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Departure)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Departure)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Destination)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Destination)
        </dd>
    </dl>

    <form asp-action="RouteDeleteConfirmed">
        <input type="hidden" asp-for="ID" />
        <input type="hidden" asp-for="BusID" />

        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="ShowRoutes" asp-route-id="@Model.BusID">Back to List</a>
    </form>
</div>

Views/Buses/Seats.cshtml
@model IEnumerable<OnlineBusTransportation.Models.Buses>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List of all Buses seats information</h1>


<button type="button" style="float:right;" class="btn btn-success" onclick="location.href='@Url.Action("Create", "Buses")'">Add New Bus</button>

@* <a asp-action="Create">Add New Bus</a>*@

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>Seats Booking Information</th>
           

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                <a asp-action="ShowBookedSeats" asp-route-id="@item.ID">Seats Booked</a>
            </td>
            
        </tr>
        }
    </tbody>
</table>

Views/Buses/ShowAllBooking.cshtml
@model IEnumerable<OnlineBusTransportation.Models.ShowBookingViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Booking money received</h3>

<table class="table">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusNumber)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Departure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                Departure Date Time
            </th>

            <th>
                Booked Seats
            </th>

            <th>
               Money Received
            </th>


        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BusNumber)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Departure)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Destination)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.datetime)
                </td>


                <td>
                    @Html.DisplayFor(modelItem => item.Seats)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.price)
                </td>
                

            </tr>
        }
    </tbody>
</table>

Views/Buses/ShowBookedSeats.cshtml
@model IEnumerable<OnlineBusTransportation.Models.BusInfo>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Routes Information(Bus Name: @TempData["Name"] & Bus Number: @TempData["BusNumber"])</h3>

<p>
   
    <button type="button" style="margin-right:1%;float:right;" class="btn btn-success" onclick="location.href = '@Url.Action("Seats", "Buses")'">Show Buses</button>

    @* <a asp-action="Create"></a>*@
</p>
<table class="table">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Departure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.datetime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.availableSeats)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookedSeats)
            </th>
            <th>
                Money Received
            </th>



        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Departure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.datetime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.availableSeats)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.BookedSeats)
            </td>
            <td>
                <a asp-action="ShowAllBooking" asp-controller="Buses" asp-route-businfoid="@item.ID">View Money Received</a>
            </td>

        </tr>
        }
    </tbody>
</table>

Views/Buses/ShowRoutes.cshtml
@model IEnumerable<OnlineBusTransportation.Models.BusInfo>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Routes Information(Bus Name: @TempData["Name"] & Bus Number: @TempData["BusNumber"])</h3>

<p>
    <button type="button" style="float:right;" class="btn btn-primary" onclick="location.href = '@Url.Action("AddRoute", "Buses", new { id = TempData["ID"]})';">Add New Route</button>
    &nbsp;
    &nbsp;

    <button type="button" style="margin-right:1%;float:right;" class="btn btn-success" onclick="location.href = '@Url.Action("Index", "Buses")'">Show Buses</button>

    @* <a asp-action="Create"></a>*@
</p>
<table class="table">

    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Departure)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.datetime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.availableSeats)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookedSeats)
            </th>

            <th>Update Information</th>


        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Departure)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Destination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.datetime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.availableSeats)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.BookedSeats)
            </td>
            <td>
                <a asp-action="EditRoute" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="RouteDelete" asp-route-id="@item.ID">Delete</a>
            </td>

        </tr>
        }
    </tbody>
</table>

Views/Buses/ViewFeedback.cshtml
@model List<UsersFeedback>

@{
    ViewData["Title"] = "Users Feedback";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List of all Users Feedback</h1>




<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Email
            </th>
            <th>
                Feedback
            </th>


        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Feedback)
                </td>

            </tr>
        }
    </tbody>
</table>